[versions]
agp = "8.13.1"
kotlin = "2.0.0"

compose-bom = "2025.01.00"
activityCompose = "1.9.3"
lifecycle = "2.8.6"

hilt = "2.52"
hiltNavigationCompose = "1.2.0"

coroutines = "1.9.0"
coreKtx = "1.13.1"
timber = "5.0.1"
desugar = "2.1.2"

junit = "4.13.2"
androidxJunit = "1.2.1"
espresso = "3.6.1"

javax-inject = { module = "javax.inject:javax.inject", version = "1" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[libraries]
# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# Core / Coroutines / Logging
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Desugaring
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

# Tests
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

javax-inject = { module = "javax.inject:javax.inject", version = "1" }

compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
